/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    passkeys: Passkey;
    media: Media;
    areas: Area;
    programas: Programa;
    modulos: Modulo;
    eventos: Evento;
    especialistas: Especialista;
    conteudos: Conteudo;
    clientes: Cliente;
    leads: Lead;
    'clientes-crm': ClienteCrm;
    propostas: Proposta;
    versoes: VersaoProposta;
    envios: EnvioProposta;
    'documentos-comerciais': DocumentoComercial;
    'eventos-comerciais': EventoComercial;
    'modelos-email': ModeloEmail;
    'envios-email': EnvioEmail;
    'linha-do-tempo': LinhaDoTempo;
    'tentativas-acesso': TentativasAcesso;
    'audit-log': AuditLog;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    passkeys: PasskeysSelect<false> | PasskeysSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    areas: AreasSelect<false> | AreasSelect<true>;
    programas: ProgramasSelect<false> | ProgramasSelect<true>;
    modulos: ModulosSelect<false> | ModulosSelect<true>;
    eventos: EventosSelect<false> | EventosSelect<true>;
    especialistas: EspecialistasSelect<false> | EspecialistasSelect<true>;
    conteudos: ConteudosSelect<false> | ConteudosSelect<true>;
    clientes: ClientesSelect<false> | ClientesSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    'clientes-crm': ClientesCrmSelect<false> | ClientesCrmSelect<true>;
    propostas: PropostasSelect<false> | PropostasSelect<true>;
    versoes: VersoesSelect<false> | VersoesSelect<true>;
    envios: EnviosSelect<false> | EnviosSelect<true>;
    'documentos-comerciais': DocumentosComerciaisSelect<false> | DocumentosComerciaisSelect<true>;
    'eventos-comerciais': EventosComerciaisSelect<false> | EventosComerciaisSelect<true>;
    'modelos-email': ModelosEmailSelect<false> | ModelosEmailSelect<true>;
    'envios-email': EnviosEmailSelect<false> | EnviosEmailSelect<true>;
    'linha-do-tempo': LinhaDoTempoSelect<false> | LinhaDoTempoSelect<true>;
    'tentativas-acesso': TentativasAcessoSelect<false> | TentativasAcessoSelect<true>;
    'audit-log': AuditLogSelect<false> | AuditLogSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    home: Home;
    'o-grupo': OGrupo;
    'corpo-docente': CorpoDocente;
    rodape: Rodape;
  };
  globalsSelect: {
    home: HomeSelect<false> | HomeSelect<true>;
    'o-grupo': OGrupoSelect<false> | OGrupoSelect<true>;
    'corpo-docente': CorpoDocenteSelect<false> | CorpoDocenteSelect<true>;
    rodape: RodapeSelect<false> | RodapeSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Nome completo do usuário (aparece em logs e em atribuições de Lead).
   */
  nome: string;
  /**
   * Define o escopo de acesso ao admin (DAB §10.1). Apenas super-administradores podem alterar.
   */
  perfil: 'super-admin' | 'editor-institucional' | 'editor-eventos' | 'atendimento-comercial';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "passkeys".
 */
export interface Passkey {
  id: number;
  usuario: number | User;
  /**
   * Nome livre pra identificar o dispositivo — ex.: "MacBook do Jotta".
   */
  apelido: string;
  credentialId: string;
  publicKey: string;
  counter: number;
  transports?: string[] | null;
  ultimoUsoEm?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Descrição alternativa para acessibilidade (WCAG 2.1 AA · CLAUDE.md §10). Imagens decorativas devem usar string vazia.
   */
  alt: string;
  /**
   * Crédito autoral exibido em legendas editoriais (ex.: "Foto: arquivo Grupo NTC").
   */
  credito?: string | null;
  /**
   * Marque quando o arquivo foi produzido pelo Grupo NTC (não derivado de fonte externa). Útil para auditoria de uso editorial.
   */
  arquivoOriginal?: boolean | null;
  prefix?: string | null;
  _objectKey?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "areas".
 */
export interface Area {
  id: number;
  /**
   * Identificador interno da área.
   */
  sigla: 'educacao' | 'gestao-publica' | 'saude';
  nome: string;
  slug: string;
  eyebrow?: string | null;
  tituloHero: string;
  subtituloHero: string;
  imagemHero: number | Media;
  /**
   * Cor de acento da área (Oxford/Cardeal/Oliva). Mantém hierarquia 60·15·10·5 da Soberana 2026.
   */
  corAcento: string;
  posicionamento: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  numerosImpacto?:
    | {
        valor: string;
        rotulo: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Programas exibidos em destaque na página da área.
   */
  programasDestacados?: (number | Programa)[] | null;
  /**
   * Campos opcionais — quando vazios, o sistema usa fallback editorial automaticamente.
   */
  seo?: {
    /**
     * Título usado na SERP e em Open Graph. Máx. 60 caracteres.
     */
    tituloSeo?: string | null;
    /**
     * Meta description e Open Graph description. Máx. 160 caracteres.
     */
    descricaoSeo?: string | null;
    /**
     * Imagem Open Graph (1200×630 recomendado).
     */
    imagemOg?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programas".
 */
export interface Programa {
  id: number;
  /**
   * Ex.: PROGE, EDUTEC, PROSUS+
   */
  sigla: string;
  nomeCompleto: string;
  eyebrow?: string | null;
  area: number | Area;
  imagemCapa?: (number | null) | Media;
  /**
   * Lockup SVG vertical do programa.
   */
  lockupSvg?: (number | null) | Media;
  cargaHorariaTotal: string;
  modulosQuantidade?: number | null;
  visaoGeral: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  problema?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  objetivo?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  metodologia?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  publicoAlvo?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  eixosTematicos?:
    | {
        titulo: string;
        descricao: string;
        id?: string | null;
      }[]
    | null;
  resultadosEsperados?:
    | {
        resultado: string;
        id?: string | null;
      }[]
    | null;
  diferenciais?:
    | {
        titulo: string;
        descricao?: string | null;
        id?: string | null;
      }[]
    | null;
  coordenacaoCientifica?: (number | Especialista)[] | null;
  docentes?: (number | Especialista)[] | null;
  modalidadesEntrega?:
    | {
        tipo: 'in-company' | 'turma-aberta' | 'sob-medida' | 'hibrida';
        descricao?: string | null;
        id?: string | null;
      }[]
    | null;
  contratacaoInstitucional?: {
    disponivel?: boolean | null;
    observacoes?: string | null;
  };
  faq?:
    | {
        pergunta: string;
        resposta: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  programasRelacionados?: (number | Programa)[] | null;
  slug: string;
  /**
   * Campos opcionais — quando vazios, o sistema usa fallback editorial automaticamente.
   */
  seo?: {
    /**
     * Título usado na SERP e em Open Graph. Máx. 60 caracteres.
     */
    tituloSeo?: string | null;
    /**
     * Meta description e Open Graph description. Máx. 160 caracteres.
     */
    descricaoSeo?: string | null;
    /**
     * Imagem Open Graph (1200×630 recomendado).
     */
    imagemOg?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "especialistas".
 */
export interface Especialista {
  id: number;
  nome: string;
  slug: string;
  /**
   * Proporção 20:23 — conforme skill ntc-palestrantes.
   */
  foto: number | Media;
  /**
   * Quando marcado, o especialista não aparece em nenhuma página pública (Corpo Docente e palestrantes de eventos). Use para quem ainda está com foto genérica. A mudança só reflete no site após publicar.
   */
  ocultarDoSite?: boolean | null;
  titulacao: 'doutorado' | 'pos-doutorado' | 'mestrado' | 'especializacao' | 'graduacao';
  instituicao: string;
  cargoAtual?: string | null;
  /**
   * 3 a 5 linhas — destaque editorial.
   */
  curriculoCurto: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  curriculoCompleto?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  linkLattes?: string | null;
  linkLinkedin?: string | null;
  linhasAtuacao?: (number | Area)[] | null;
  /**
   * Vertical institucional do especialista. Usado em filtros do Corpo Docente e em listagens por vertical.
   */
  vertical?: ('educacao' | 'gestao-publica' | 'saude') | null;
  /**
   * Camada de autoridade da curadoria (doc 25 — 5 camadas).
   */
  tipo?: ('autoridade' | 'palestrante' | 'doutrinador' | 'consultor' | 'pesquisador') | null;
  /**
   * Marcador opcional: 'contratacoes' indica que o especialista compõe o núcleo Contratações Públicas dentro de Gestão Pública.
   */
  frente?: 'contratacoes' | null;
  /**
   * Maior titulação relevante para o dataset de filtro.
   */
  formacao?: ('doutorado' | 'mestrado' | 'especializacao' | 'graduacao-experiencia') | null;
  /**
   * Esferas de atuação profissional (múltipla escolha).
   */
  atuacao?:
    | (
        | 'universidade'
        | 'gestao-publica'
        | 'controle'
        | 'judiciario'
        | 'multilateral'
        | 'terceiro-setor'
        | 'consultoria'
      )[]
    | null;
  /**
   * Programas em que o especialista figura como referência. Usado para derivar o dataset de filtro 'programas' no FilterBarDocentes.
   */
  programasRelacionados?: (number | Programa)[] | null;
  /**
   * [Reservado v2 — perfil público na OTT própria]
   */
  apresentacaoOTT?: {
    ativo?: boolean | null;
    biografiaEstendida?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "modulos".
 */
export interface Modulo {
  id: number;
  programa: number | Programa;
  numero: number;
  titulo: string;
  ementa: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  cargaHoraria?: string | null;
  /**
   * Eventos abertos que derivam deste módulo.
   */
  eventosVinculados?: (number | Evento)[] | null;
  /**
   * Usado pelo módulo CRM do painel; o site ignora este grupo.
   */
  comercial?: {
    tituloComercial?: string | null;
    /**
     * Valor de referência (R$).
     */
    valor?: number | null;
    replay?: string | null;
    certificacao?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "eventos".
 */
export interface Evento {
  id: number;
  nome: string;
  eyebrow?: string | null;
  /**
   * Programa do qual o evento deriva (opcional).
   */
  programa?: (number | null) | Programa;
  area: number | Area;
  imagemCapa: number | Media;
  dataInicio: string;
  dataFim?: string | null;
  fusoHorario?: string | null;
  modalidade: 'online' | 'presencial' | 'hibrido';
  local?: {
    nomeLocal?: string | null;
    endereco?: string | null;
    cidade?: string | null;
    estado?: string | null;
  };
  cargaHoraria: string;
  resumo: string;
  publicoAlvo?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  objetivos?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  conteudoProgramatico?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  programacaoDetalhada?:
    | {
        horario: string;
        titulo: string;
        descricao?: string | null;
        palestrante?: (number | Especialista)[] | null;
        id?: string | null;
      }[]
    | null;
  palestrantes?: (number | Especialista)[] | null;
  diferenciais?:
    | {
        titulo?: string | null;
        descricao?: string | null;
        id?: string | null;
      }[]
    | null;
  inscricaoAberta?: boolean | null;
  /**
   * PDF do folder do evento. Quando preenchido, o botão 'Baixar folder' da página passa a baixar este arquivo.
   */
  folderPdf?: (number | null) | Media;
  /**
   * URL da plataforma terceira de inscrição (v1).
   */
  linkInscricaoExterna?: string | null;
  /**
   * Plataforma que processa a inscrição (provisório v1).
   */
  plataformaTerceira?: ('sympla' | 'even3' | 'eventbrite' | 'webinar-atual' | 'outra') | null;
  /**
   * Ex.: "Gratuito" · "R$ 480" · "Sob proposta"
   */
  valor?: string | null;
  vagasLimitadas?: boolean | null;
  totalVagas?: number | null;
  /**
   * [Reservado v2 — OTT própria] Ativado quando plataforma própria estiver pronta.
   */
  inscricaoNativa?: {
    ativa?: boolean | null;
    idEventoOTT?: string | null;
  };
  replayDisponivel?: boolean | null;
  linkReplay?: string | null;
  prazoReplay?: string | null;
  certificadoEmitido?: boolean | null;
  observacoesCertificado?: string | null;
  eventosRelacionados?: (number | Evento)[] | null;
  faq?:
    | {
        pergunta: string;
        resposta: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  slug: string;
  /**
   * Campos opcionais — quando vazios, o sistema usa fallback editorial automaticamente.
   */
  seo?: {
    /**
     * Título usado na SERP e em Open Graph. Máx. 60 caracteres.
     */
    tituloSeo?: string | null;
    /**
     * Meta description e Open Graph description. Máx. 160 caracteres.
     */
    descricaoSeo?: string | null;
    /**
     * Imagem Open Graph (1200×630 recomendado).
     */
    imagemOg?: (number | null) | Media;
  };
  /**
   * Usado pelo módulo CRM do painel; o site ignora este grupo.
   */
  comercial?: {
    /**
     * Código comercial do produto (CRM legado).
     */
    codigo?: string | null;
    /**
     * Valor de referência (R$).
     */
    valor?: number | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "conteudos".
 */
export interface Conteudo {
  id: number;
  titulo: string;
  slug: string;
  categoria: 'artigo' | 'estudo' | 'nota-tecnica' | 'webinar' | 'material' | 'noticia';
  area?: (number | null) | Area;
  lide: string;
  imagemDestaque?: (number | null) | Media;
  corpo: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  autor?: (number | Especialista)[] | null;
  dataPublicacao: string;
  /**
   * Assinatura institucional (ex.: Curadoria NTC Saúde). Use quando o conteúdo não é assinado por um especialista do corpo docente.
   */
  assinatura?: string | null;
  /**
   * Aparece na seção Destaques de /conteudos (os 3 mais recentes).
   */
  destaque?: boolean | null;
  /**
   * Enquanto rascunho, aparece no site como "Em preparação editorial", sem link. Ignorado depois de publicado.
   */
  anunciarEmPreparacao?: boolean | null;
  /**
   * Calculado a partir do corpo.
   */
  tempoLeituraMin?: number | null;
  /**
   * URL do webinar gravado ou do material hospedado fora (opcional).
   */
  linkExterno?: string | null;
  anexoDownload?: (number | null) | Media;
  conteudosRelacionados?: (number | Conteudo)[] | null;
  /**
   * Campos opcionais — quando vazios, o sistema usa fallback editorial automaticamente.
   */
  seo?: {
    /**
     * Título usado na SERP e em Open Graph. Máx. 60 caracteres.
     */
    tituloSeo?: string | null;
    /**
     * Meta description e Open Graph description. Máx. 160 caracteres.
     */
    descricaoSeo?: string | null;
    /**
     * Imagem Open Graph (1200×630 recomendado).
     */
    imagemOg?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clientes".
 */
export interface Cliente {
  id: number;
  nome: string;
  logo: number | Media;
  esfera: 'municipal' | 'estadual' | 'federal' | 'privada' | 'terceiro-setor';
  estado?: string | null;
  cidade?: string | null;
  areasAtendidas?: (number | Area)[] | null;
  descricaoBreve?: string | null;
  destaqueHome?: boolean | null;
  ordem?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  tipo: 'proposta' | 'contato' | 'newsletter' | 'candidatura';
  identificacao?: string | null;
  observacoesInternas?: string | null;
  /**
   * Coluna do kanban comercial.
   */
  estagio:
    | 'lead'
    | 'oportunidade'
    | 'em-contato'
    | 'proposta-em-producao'
    | 'proposta-enviada'
    | 'proposta-aceita'
    | 'evento-agendado'
    | 'contrato-recebido'
    | 'links-enviados'
    | 'evento-realizado';
  perdido?: boolean | null;
  motivoPerda?: ('sem-resposta' | 'recusou' | 'sem-orcamento' | 'cancelado' | 'outro') | null;
  perdidoEm?: string | null;
  detalhePerda?: string | null;
  cliente?: (number | null) | ClienteCrm;
  clienteCasadoPor?: ('cnpj' | 'dominio' | 'nome' | 'criado' | 'manual') | null;
  responsavel?: (number | null) | User;
  valorEstimado?: number | null;
  dataPrevistaEvento?: string | null;
  observacoes?: string | null;
  origemEntrada: 'site' | 'manual' | 'whatsapp';
  nome: string;
  email: string;
  telefone?: string | null;
  cargo?: string | null;
  instituicao?: string | null;
  esfera?: ('municipal' | 'estadual' | 'federal' | 'privada' | 'terceiro-setor') | null;
  detalhesProposta?: {
    programa?: (number | null) | Programa;
    modalidade?: ('in-company' | 'turma-aberta' | 'sob-medida' | 'proposta-livre') | null;
    participantesEstimados?: number | null;
    mensagem?: string | null;
  };
  detalhesContato?: {
    assunto?: ('imprensa' | 'parcerias' | 'fornecedor' | 'duvida-institucional' | 'outro') | null;
    mensagem?: string | null;
  };
  detalhesNewsletter?: {
    areasInteresse?: (number | Area)[] | null;
  };
  detalhesCandidatura?: {
    titulacao?: string | null;
    linhasAtuacao?: (number | Area)[] | null;
    apresentacao?: string | null;
    linkLattes?: string | null;
    linkLinkedin?: string | null;
    curriculo?: (number | null) | Media;
  };
  /**
   * Página, referrer e UTMs no momento do submit.
   */
  origem?: {
    paginaSubmissao?: string | null;
    referrer?: string | null;
    utmSource?: string | null;
    utmMedium?: string | null;
    utmCampaign?: string | null;
    utmTerm?: string | null;
    utmContent?: string | null;
  };
  /**
   * Registro do aceite LGPD (CLAUDE.md §12).
   */
  consentimentoLgpd: {
    aceito: boolean;
    timestamp?: string | null;
    politicaVersao?: string | null;
    ipSubmissao?: string | null;
  };
  payloadBruto?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clientes-crm".
 */
export interface ClienteCrm {
  id: number;
  orgao: string;
  sigla?: string | null;
  tipo?:
    | (
        | 'secretaria-federal'
        | 'secretaria-estadual'
        | 'secretaria-municipal'
        | 'autarquia'
        | 'fundacao'
        | 'tribunal'
        | 'camara'
        | 'assembleia'
        | 'consorcio'
        | 'escola-de-governo'
        | 'outro'
      )
    | null;
  municipio?: string | null;
  uf?:
    | (
        | 'AC'
        | 'AL'
        | 'AM'
        | 'AP'
        | 'BA'
        | 'CE'
        | 'DF'
        | 'ES'
        | 'GO'
        | 'MA'
        | 'MG'
        | 'MS'
        | 'MT'
        | 'PA'
        | 'PB'
        | 'PE'
        | 'PI'
        | 'PR'
        | 'RJ'
        | 'RN'
        | 'RO'
        | 'RR'
        | 'RS'
        | 'SC'
        | 'SE'
        | 'SP'
        | 'TO'
      )
    | null;
  esfera?:
    | (
        | 'municipal'
        | 'estadual'
        | 'federal'
        | 'consorcio'
        | 'autarquia'
        | 'fundacao'
        | 'escola-de-governo'
        | 'tribunal'
        | 'camara'
        | 'assembleia'
        | 'outros'
      )
    | null;
  area?:
    | (
        | 'educacao'
        | 'gestao-publica'
        | 'governanca'
        | 'licitacoes-e-contratos'
        | 'inovacao'
        | 'saude'
        | 'assistencia-social'
        | 'controle-interno'
        | 'juridico'
        | 'alta-gestao'
      )
    | null;
  cnpj?: string | null;
  email?: string | null;
  origem?: ('lead-site' | 'manual' | 'importado') | null;
  /**
   * Pessoas do órgão. No máximo um contato principal.
   */
  contatos?:
    | {
        nome: string;
        cargo?: string | null;
        setor?: string | null;
        email?: string | null;
        whatsapp?: string | null;
        principal?: boolean | null;
        decisor?: boolean | null;
        id?: string | null;
      }[]
    | null;
  responsavel?: (number | null) | User;
  observacoes?: string | null;
  /**
   * Instituição correspondente na vitrine do site, se houver.
   */
  clienteSite?: (number | null) | Cliente;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "propostas".
 */
export interface Proposta {
  id: number;
  codigoBase: string;
  codigo: string;
  versao?: number | null;
  lead?: (number | null) | Lead;
  cliente: number | ClienteCrm;
  programa?: (number | null) | Programa;
  tipo?: ('programa-completo' | 'modulo-avulso' | 'produto-evento-avulso' | 'customizada') | null;
  status?: ('rascunho' | 'enviada' | 'em-analise' | 'aprovada' | 'recusada' | 'substituida' | 'expirada') | null;
  modulos?: (number | Modulo)[] | null;
  eventos?: (number | Evento)[] | null;
  valorUnitario?: number | null;
  qtdPagantes?: number | null;
  cortesias?: number | null;
  percDesconto?: number | null;
  /**
   * Derivado.
   */
  valorBruto?: number | null;
  /**
   * Derivado.
   */
  desconto?: number | null;
  /**
   * Derivado.
   */
  valorLiquido?: number | null;
  modalidade?: string | null;
  replay?: string | null;
  condPagto?: string | null;
  condEspecificas?: string | null;
  observacoes?: string | null;
  textoApresentacao?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  textoContexto?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  textoObjetivos?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  textoPublicoAlvo?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  textoMetodologia?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  textoEventon?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  textoCertificacaoReplay?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  textoCancelamento?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  textoProtecaoConteudo?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  textoFundamentacaoLegal?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  textoProximosPassos?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  textoFechamento?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  eixos?:
    | {
        titulo?: string | null;
        descricao?: string | null;
        id?: string | null;
      }[]
    | null;
  diferenciais?:
    | {
        titulo?: string | null;
        descricao?: string | null;
        id?: string | null;
      }[]
    | null;
  resultados?:
    | {
        texto?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Escolher da coleção preenche nome e credencial; entrada livre é permitida.
   */
  docentes?:
    | {
        especialista?: (number | null) | Especialista;
        nome?: string | null;
        credencial?: string | null;
        eixo?: string | null;
        id?: string | null;
      }[]
    | null;
  modulosDetalhados?:
    | {
        modulo?: (number | null) | Modulo;
        tituloExibido?: string | null;
        ementa?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Seções livres do documento (observações, anexos textuais).
   */
  secoesExtras?:
    | {
        titulo?: string | null;
        corpo?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        posicao?: ('antes-quadro-comercial' | 'apos-condicoes-comerciais' | 'fim') | null;
        id?: string | null;
      }[]
    | null;
  elaborador?: (number | null) | User;
  aprovador?: (number | null) | User;
  validadeDias?: number | null;
  dataCriacao?: string | null;
  validade?: string | null;
  motivoRevisao?: string | null;
  /**
   * Código da versão substituída.
   */
  substitui?: string | null;
  /**
   * Gerado pelo botão 'Gerar PDF' na tela de detalhe.
   */
  pdfGerado?: (number | null) | DocumentoComercial;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documentos-comerciais".
 */
export interface DocumentoComercial {
  id: number;
  alt?: string | null;
  descricao?: string | null;
  evento?: (number | null) | EventoComercial;
  prefix?: string | null;
  _objectKey?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "eventos-comerciais".
 */
export interface EventoComercial {
  id: number;
  lead?: (number | null) | Lead;
  cliente: number | ClienteCrm;
  proposta?: (number | null) | Proposta;
  titulo: string;
  dataInicio: string;
  dataFim?: string | null;
  modalidade?: ('presencial' | 'online' | 'hibrido') | null;
  local?: string | null;
  moduloCatalogo?: (number | null) | Modulo;
  contratoEmpenho?: {
    tipo?: ('contrato' | 'empenho' | 'termo' | 'outro') | null;
    numero?: string | null;
    data?: string | null;
    valor?: number | null;
    arquivo?: (number | null) | DocumentoComercial;
  };
  linksInscricao?:
    | {
        rotulo: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  status: 'agendado' | 'realizado' | 'cancelado';
  observacoes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "versoes".
 */
export interface VersaoProposta {
  id: number;
  codBase: string;
  nVersao?: number | null;
  proposta?: (number | null) | Proposta;
  data?: string | null;
  substitui?: string | null;
  motivo?: string | null;
  sintese?: string | null;
  statusAnterior?: string | null;
  vigente?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "envios".
 */
export interface EnvioProposta {
  id: number;
  proposta: number | Proposta;
  data?: string | null;
  canal?: ('e-mail' | 'whatsapp' | 'oficio' | 'presencial' | 'outro') | null;
  destinatarios?: string | null;
  status?: ('enviada' | 'recebida' | 'em-analise' | 'respondida') | null;
  observacoes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "modelos-email".
 */
export interface ModeloEmail {
  id: number;
  nome: string;
  finalidade: 'proposta' | 'documentos' | 'links-inscricao' | 'livre';
  padrao?: boolean | null;
  assunto: string;
  corpo: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  anexarPdfProposta?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "envios-email".
 */
export interface EnvioEmail {
  id: number;
  lead?: (number | null) | Lead;
  cliente?: (number | null) | ClienteCrm;
  modelo?: (number | null) | ModeloEmail;
  finalidade: 'proposta' | 'documentos' | 'links-inscricao' | 'livre';
  destinatarios: string;
  copia?: string | null;
  assunto: string;
  corpoRenderizado: string;
  anexos?: (number | DocumentoComercial)[] | null;
  enviadoPor?: (number | null) | User;
  enviadoEm: string;
  idResend?: string | null;
  status: 'enviado' | 'falhou';
  erro?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "linha-do-tempo".
 */
export interface LinhaDoTempo {
  id: number;
  cliente: number | ClienteCrm;
  lead?: (number | null) | Lead;
  tipo:
    | 'lead'
    | 'transicao'
    | 'perda'
    | 'reabertura'
    | 'email'
    | 'proposta'
    | 'evento'
    | 'documento'
    | 'vinculo'
    | 'nota';
  titulo: string;
  detalhe?: string | null;
  referencia?: {
    colecao?: string | null;
    id?: string | null;
  };
  usuario?: (number | null) | User;
  em: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Lastro efêmero do rate limit. Linhas se apagam sozinhas fora da janela.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tentativas-acesso".
 */
export interface TentativasAcesso {
  id: number;
  rota: string;
  ip: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-log".
 */
export interface AuditLog {
  id: number;
  usuario?: (number | null) | User;
  acao?: ('criar' | 'atualizar' | 'publicar' | 'despublicar' | 'deletar' | 'login' | 'logout') | null;
  entidade?: string | null;
  entidadeId?: string | null;
  descricao?: string | null;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  ip?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'passkeys';
        value: number | Passkey;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'areas';
        value: number | Area;
      } | null)
    | ({
        relationTo: 'programas';
        value: number | Programa;
      } | null)
    | ({
        relationTo: 'modulos';
        value: number | Modulo;
      } | null)
    | ({
        relationTo: 'eventos';
        value: number | Evento;
      } | null)
    | ({
        relationTo: 'especialistas';
        value: number | Especialista;
      } | null)
    | ({
        relationTo: 'conteudos';
        value: number | Conteudo;
      } | null)
    | ({
        relationTo: 'clientes';
        value: number | Cliente;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'clientes-crm';
        value: number | ClienteCrm;
      } | null)
    | ({
        relationTo: 'propostas';
        value: number | Proposta;
      } | null)
    | ({
        relationTo: 'versoes';
        value: number | VersaoProposta;
      } | null)
    | ({
        relationTo: 'envios';
        value: number | EnvioProposta;
      } | null)
    | ({
        relationTo: 'documentos-comerciais';
        value: number | DocumentoComercial;
      } | null)
    | ({
        relationTo: 'eventos-comerciais';
        value: number | EventoComercial;
      } | null)
    | ({
        relationTo: 'modelos-email';
        value: number | ModeloEmail;
      } | null)
    | ({
        relationTo: 'envios-email';
        value: number | EnvioEmail;
      } | null)
    | ({
        relationTo: 'linha-do-tempo';
        value: number | LinhaDoTempo;
      } | null)
    | ({
        relationTo: 'tentativas-acesso';
        value: number | TentativasAcesso;
      } | null)
    | ({
        relationTo: 'audit-log';
        value: number | AuditLog;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  nome?: T;
  perfil?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "passkeys_select".
 */
export interface PasskeysSelect<T extends boolean = true> {
  usuario?: T;
  apelido?: T;
  credentialId?: T;
  publicKey?: T;
  counter?: T;
  transports?: T;
  ultimoUsoEm?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  credito?: T;
  arquivoOriginal?: T;
  prefix?: T;
  _objectKey?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "areas_select".
 */
export interface AreasSelect<T extends boolean = true> {
  sigla?: T;
  nome?: T;
  slug?: T;
  eyebrow?: T;
  tituloHero?: T;
  subtituloHero?: T;
  imagemHero?: T;
  corAcento?: T;
  posicionamento?: T;
  numerosImpacto?:
    | T
    | {
        valor?: T;
        rotulo?: T;
        id?: T;
      };
  programasDestacados?: T;
  seo?:
    | T
    | {
        tituloSeo?: T;
        descricaoSeo?: T;
        imagemOg?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programas_select".
 */
export interface ProgramasSelect<T extends boolean = true> {
  sigla?: T;
  nomeCompleto?: T;
  eyebrow?: T;
  area?: T;
  imagemCapa?: T;
  lockupSvg?: T;
  cargaHorariaTotal?: T;
  modulosQuantidade?: T;
  visaoGeral?: T;
  problema?: T;
  objetivo?: T;
  metodologia?: T;
  publicoAlvo?: T;
  eixosTematicos?:
    | T
    | {
        titulo?: T;
        descricao?: T;
        id?: T;
      };
  resultadosEsperados?:
    | T
    | {
        resultado?: T;
        id?: T;
      };
  diferenciais?:
    | T
    | {
        titulo?: T;
        descricao?: T;
        id?: T;
      };
  coordenacaoCientifica?: T;
  docentes?: T;
  modalidadesEntrega?:
    | T
    | {
        tipo?: T;
        descricao?: T;
        id?: T;
      };
  contratacaoInstitucional?:
    | T
    | {
        disponivel?: T;
        observacoes?: T;
      };
  faq?:
    | T
    | {
        pergunta?: T;
        resposta?: T;
        id?: T;
      };
  programasRelacionados?: T;
  slug?: T;
  seo?:
    | T
    | {
        tituloSeo?: T;
        descricaoSeo?: T;
        imagemOg?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "modulos_select".
 */
export interface ModulosSelect<T extends boolean = true> {
  programa?: T;
  numero?: T;
  titulo?: T;
  ementa?: T;
  cargaHoraria?: T;
  eventosVinculados?: T;
  comercial?:
    | T
    | {
        tituloComercial?: T;
        valor?: T;
        replay?: T;
        certificacao?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "eventos_select".
 */
export interface EventosSelect<T extends boolean = true> {
  nome?: T;
  eyebrow?: T;
  programa?: T;
  area?: T;
  imagemCapa?: T;
  dataInicio?: T;
  dataFim?: T;
  fusoHorario?: T;
  modalidade?: T;
  local?:
    | T
    | {
        nomeLocal?: T;
        endereco?: T;
        cidade?: T;
        estado?: T;
      };
  cargaHoraria?: T;
  resumo?: T;
  publicoAlvo?: T;
  objetivos?: T;
  conteudoProgramatico?: T;
  programacaoDetalhada?:
    | T
    | {
        horario?: T;
        titulo?: T;
        descricao?: T;
        palestrante?: T;
        id?: T;
      };
  palestrantes?: T;
  diferenciais?:
    | T
    | {
        titulo?: T;
        descricao?: T;
        id?: T;
      };
  inscricaoAberta?: T;
  folderPdf?: T;
  linkInscricaoExterna?: T;
  plataformaTerceira?: T;
  valor?: T;
  vagasLimitadas?: T;
  totalVagas?: T;
  inscricaoNativa?:
    | T
    | {
        ativa?: T;
        idEventoOTT?: T;
      };
  replayDisponivel?: T;
  linkReplay?: T;
  prazoReplay?: T;
  certificadoEmitido?: T;
  observacoesCertificado?: T;
  eventosRelacionados?: T;
  faq?:
    | T
    | {
        pergunta?: T;
        resposta?: T;
        id?: T;
      };
  slug?: T;
  seo?:
    | T
    | {
        tituloSeo?: T;
        descricaoSeo?: T;
        imagemOg?: T;
      };
  comercial?:
    | T
    | {
        codigo?: T;
        valor?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "especialistas_select".
 */
export interface EspecialistasSelect<T extends boolean = true> {
  nome?: T;
  slug?: T;
  foto?: T;
  ocultarDoSite?: T;
  titulacao?: T;
  instituicao?: T;
  cargoAtual?: T;
  curriculoCurto?: T;
  curriculoCompleto?: T;
  linkLattes?: T;
  linkLinkedin?: T;
  linhasAtuacao?: T;
  vertical?: T;
  tipo?: T;
  frente?: T;
  formacao?: T;
  atuacao?: T;
  programasRelacionados?: T;
  apresentacaoOTT?:
    | T
    | {
        ativo?: T;
        biografiaEstendida?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "conteudos_select".
 */
export interface ConteudosSelect<T extends boolean = true> {
  titulo?: T;
  slug?: T;
  categoria?: T;
  area?: T;
  lide?: T;
  imagemDestaque?: T;
  corpo?: T;
  autor?: T;
  dataPublicacao?: T;
  assinatura?: T;
  destaque?: T;
  anunciarEmPreparacao?: T;
  tempoLeituraMin?: T;
  linkExterno?: T;
  anexoDownload?: T;
  conteudosRelacionados?: T;
  seo?:
    | T
    | {
        tituloSeo?: T;
        descricaoSeo?: T;
        imagemOg?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clientes_select".
 */
export interface ClientesSelect<T extends boolean = true> {
  nome?: T;
  logo?: T;
  esfera?: T;
  estado?: T;
  cidade?: T;
  areasAtendidas?: T;
  descricaoBreve?: T;
  destaqueHome?: T;
  ordem?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  tipo?: T;
  identificacao?: T;
  observacoesInternas?: T;
  estagio?: T;
  perdido?: T;
  motivoPerda?: T;
  perdidoEm?: T;
  detalhePerda?: T;
  cliente?: T;
  clienteCasadoPor?: T;
  responsavel?: T;
  valorEstimado?: T;
  dataPrevistaEvento?: T;
  observacoes?: T;
  origemEntrada?: T;
  nome?: T;
  email?: T;
  telefone?: T;
  cargo?: T;
  instituicao?: T;
  esfera?: T;
  detalhesProposta?:
    | T
    | {
        programa?: T;
        modalidade?: T;
        participantesEstimados?: T;
        mensagem?: T;
      };
  detalhesContato?:
    | T
    | {
        assunto?: T;
        mensagem?: T;
      };
  detalhesNewsletter?:
    | T
    | {
        areasInteresse?: T;
      };
  detalhesCandidatura?:
    | T
    | {
        titulacao?: T;
        linhasAtuacao?: T;
        apresentacao?: T;
        linkLattes?: T;
        linkLinkedin?: T;
        curriculo?: T;
      };
  origem?:
    | T
    | {
        paginaSubmissao?: T;
        referrer?: T;
        utmSource?: T;
        utmMedium?: T;
        utmCampaign?: T;
        utmTerm?: T;
        utmContent?: T;
      };
  consentimentoLgpd?:
    | T
    | {
        aceito?: T;
        timestamp?: T;
        politicaVersao?: T;
        ipSubmissao?: T;
      };
  payloadBruto?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clientes-crm_select".
 */
export interface ClientesCrmSelect<T extends boolean = true> {
  orgao?: T;
  sigla?: T;
  tipo?: T;
  municipio?: T;
  uf?: T;
  esfera?: T;
  area?: T;
  cnpj?: T;
  email?: T;
  origem?: T;
  contatos?:
    | T
    | {
        nome?: T;
        cargo?: T;
        setor?: T;
        email?: T;
        whatsapp?: T;
        principal?: T;
        decisor?: T;
        id?: T;
      };
  responsavel?: T;
  observacoes?: T;
  clienteSite?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "propostas_select".
 */
export interface PropostasSelect<T extends boolean = true> {
  codigoBase?: T;
  codigo?: T;
  versao?: T;
  lead?: T;
  cliente?: T;
  programa?: T;
  tipo?: T;
  status?: T;
  modulos?: T;
  eventos?: T;
  valorUnitario?: T;
  qtdPagantes?: T;
  cortesias?: T;
  percDesconto?: T;
  valorBruto?: T;
  desconto?: T;
  valorLiquido?: T;
  modalidade?: T;
  replay?: T;
  condPagto?: T;
  condEspecificas?: T;
  observacoes?: T;
  textoApresentacao?: T;
  textoContexto?: T;
  textoObjetivos?: T;
  textoPublicoAlvo?: T;
  textoMetodologia?: T;
  textoEventon?: T;
  textoCertificacaoReplay?: T;
  textoCancelamento?: T;
  textoProtecaoConteudo?: T;
  textoFundamentacaoLegal?: T;
  textoProximosPassos?: T;
  textoFechamento?: T;
  eixos?:
    | T
    | {
        titulo?: T;
        descricao?: T;
        id?: T;
      };
  diferenciais?:
    | T
    | {
        titulo?: T;
        descricao?: T;
        id?: T;
      };
  resultados?:
    | T
    | {
        texto?: T;
        id?: T;
      };
  docentes?:
    | T
    | {
        especialista?: T;
        nome?: T;
        credencial?: T;
        eixo?: T;
        id?: T;
      };
  modulosDetalhados?:
    | T
    | {
        modulo?: T;
        tituloExibido?: T;
        ementa?: T;
        id?: T;
      };
  secoesExtras?:
    | T
    | {
        titulo?: T;
        corpo?: T;
        posicao?: T;
        id?: T;
      };
  elaborador?: T;
  aprovador?: T;
  validadeDias?: T;
  dataCriacao?: T;
  validade?: T;
  motivoRevisao?: T;
  substitui?: T;
  pdfGerado?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "versoes_select".
 */
export interface VersoesSelect<T extends boolean = true> {
  codBase?: T;
  nVersao?: T;
  proposta?: T;
  data?: T;
  substitui?: T;
  motivo?: T;
  sintese?: T;
  statusAnterior?: T;
  vigente?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "envios_select".
 */
export interface EnviosSelect<T extends boolean = true> {
  proposta?: T;
  data?: T;
  canal?: T;
  destinatarios?: T;
  status?: T;
  observacoes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documentos-comerciais_select".
 */
export interface DocumentosComerciaisSelect<T extends boolean = true> {
  alt?: T;
  descricao?: T;
  evento?: T;
  prefix?: T;
  _objectKey?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "eventos-comerciais_select".
 */
export interface EventosComerciaisSelect<T extends boolean = true> {
  lead?: T;
  cliente?: T;
  proposta?: T;
  titulo?: T;
  dataInicio?: T;
  dataFim?: T;
  modalidade?: T;
  local?: T;
  moduloCatalogo?: T;
  contratoEmpenho?:
    | T
    | {
        tipo?: T;
        numero?: T;
        data?: T;
        valor?: T;
        arquivo?: T;
      };
  linksInscricao?:
    | T
    | {
        rotulo?: T;
        url?: T;
        id?: T;
      };
  status?: T;
  observacoes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "modelos-email_select".
 */
export interface ModelosEmailSelect<T extends boolean = true> {
  nome?: T;
  finalidade?: T;
  padrao?: T;
  assunto?: T;
  corpo?: T;
  anexarPdfProposta?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "envios-email_select".
 */
export interface EnviosEmailSelect<T extends boolean = true> {
  lead?: T;
  cliente?: T;
  modelo?: T;
  finalidade?: T;
  destinatarios?: T;
  copia?: T;
  assunto?: T;
  corpoRenderizado?: T;
  anexos?: T;
  enviadoPor?: T;
  enviadoEm?: T;
  idResend?: T;
  status?: T;
  erro?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "linha-do-tempo_select".
 */
export interface LinhaDoTempoSelect<T extends boolean = true> {
  cliente?: T;
  lead?: T;
  tipo?: T;
  titulo?: T;
  detalhe?: T;
  referencia?:
    | T
    | {
        colecao?: T;
        id?: T;
      };
  usuario?: T;
  em?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tentativas-acesso_select".
 */
export interface TentativasAcessoSelect<T extends boolean = true> {
  rota?: T;
  ip?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-log_select".
 */
export interface AuditLogSelect<T extends boolean = true> {
  usuario?: T;
  acao?: T;
  entidade?: T;
  entidadeId?: T;
  descricao?: T;
  metadata?: T;
  ip?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: number;
  /**
   * Hero único, usado APENAS como fallback quando heroSlider não tem slides preenchidos. A Home v3 Premium usa heroSlider.
   */
  hero?: {
    eyebrow?: string | null;
    titulo?: string | null;
    subtitulo?: string | null;
    imagem?: (number | null) | Media;
    ctas?:
      | {
          rotulo: string;
          link: string;
          variante?: ('primario' | 'secundario') | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Vitrine editorial da Home v3 Premium (até 6 slides com autoplay 7s e parallax). Quando há ao menos 1 slide preenchido, este slider substitui o hero único acima.
   */
  heroSlider?: {
    /**
     * Intervalo de troca de slides em milissegundos. Padrão 7000 (7s). Mínimo 3000 por acessibilidade (WCAG 2.2.2).
     */
    intervaloMs?: number | null;
    /**
     * Cada slide herda o vocabulário de doc 13 §2.1 — tipo, eyebrow, título (com sintaxe <accent>palavra</accent> para destaque dourado italic), subtítulo, pílula de evento opcional, CTAs (até 3).
     */
    slides?:
      | {
          tipo: 'institucional' | 'evento' | 'programa' | 'solucao' | 'eventon';
          imagem: number | Media;
          eyebrow: string;
          /**
           * Use <accent>palavra</accent> para marcar a palavra ou expressão destacada em dourado italic. Ex.: 'Capacitações <accent>sob medida</accent> para a sua instituição.'
           */
          titulo: string;
          subtitulo: string;
          /**
           * Pílula de resumo de evento (data, local, modalidade). Preencha apenas em slides com tipo=evento.
           */
          eventoPill?: {
            data?: string | null;
            local?: string | null;
            modalidade?: string | null;
          };
          ctas?:
            | {
                rotulo: string;
                link: string;
                variante?: ('primario' | 'secundario' | 'textlink') | null;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
  };
  destaquesEditoriais?:
    | {
        titulo: string;
        resumo: string;
        imagem: number | Media;
        link: string;
        eyebrow?: string | null;
        id?: string | null;
      }[]
    | null;
  areasEmFoco?: (number | Area)[] | null;
  /**
   * Eventos exibidos na seção de agenda da Home.
   */
  eventosAgendaDestaque?: (number | Evento)[] | null;
  numerosImpacto?:
    | {
        valor: string;
        rotulo: string;
        id?: string | null;
      }[]
    | null;
  clientesDestaque?: (number | Cliente)[] | null;
  ctaInstitucional?: {
    titulo?: string | null;
    descricao?: string | null;
    rotuloCta?: string | null;
    linkCta?: string | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "o-grupo".
 */
export interface OGrupo {
  id: number;
  hero?: {
    eyebrow?: string | null;
    titulo?: string | null;
    subtitulo?: string | null;
    imagem?: (number | null) | Media;
  };
  /**
   * Quem somos. Texto editorial curto, 2-3 parágrafos.
   */
  apresentacao?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Origens, marcos e evolução.
   */
  trajetoria?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Onde nos colocamos diante do ecossistema público.
   */
  posicionamento?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  numerosImpacto?:
    | {
        valor: string;
        rotulo: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Como entregamos. Pilares, princípios, abordagem.
   */
  metodologia?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Especialistas exibidos em destaque no /o-grupo. Em vazio, a seção é omitida.
   */
  especialistasDestaque?: (number | Especialista)[] | null;
  /**
   * Clientes exibidos em destaque no /o-grupo. Em vazio, a seção é omitida.
   */
  clientesDestaque?: (number | Cliente)[] | null;
  ctaInstitucional?: {
    titulo?: string | null;
    descricao?: string | null;
    rotuloCta?: string | null;
    linkCta?: string | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "corpo-docente".
 */
export interface CorpoDocente {
  id: number;
  hero: {
    eyebrow: string;
    /**
     * Aceita <span class='accent'> e <br>. Lexical restritivo aplicado globalmente.
     */
    titulo: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    /**
     * Aceita <em>. Lexical restritivo.
     */
    subtitulo: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    quicklinks?:
      | {
          tipo: 'anchor' | 'tab';
          rotulo: string;
          href?: string | null;
          vertShortcut?: ('todos' | 'educacao' | 'gestao-publica' | 'contratacoes' | 'saude') | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * 4 cards de números: Educação · Gestão Pública · Núcleo Contratações · Saúde.
   */
  metricas?:
    | {
        classe: 'is-edu' | 'is-gov' | 'is-cpr' | 'is-sau';
        sublabel: string;
        /**
         * Número exibido (ex: '60', '31', '5').
         */
        num: string;
        label: string;
        detalhe: string;
        id?: string | null;
      }[]
    | null;
  marker: string;
  /**
   * Aceita <em>.
   */
  tituloManifesto: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  lede: string;
  /**
   * Educação · Gestão Pública · Contratações · Saúde.
   */
  archCards?:
    | {
        area: 'educacao' | 'gestao-publica' | 'contratacoes' | 'saude';
        eyebrow: string;
        tituloArch: string;
        descricao: string;
        selo: string;
        id?: string | null;
      }[]
    | null;
  /**
   * 5 camadas de autoridade (01..05).
   */
  camadas?:
    | {
        num: string;
        tituloCamada: string;
        descricao: string;
        id?: string | null;
      }[]
    | null;
  callout: {
    tituloCallout: string;
    descricao: string;
  };
  /**
   * Aceita <strong>.
   */
  nota: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Lista única ordenável. Cada item tem 'formato' (featured/expert/axis) que decide quais campos aparecem. Cards featured/expert apontam para Especialistas; cards axis (Saúde) são narrativas de eixo sem pessoa relacionada.
   */
  cards?:
    | {
        formato: 'featured' | 'expert' | 'axis';
        /**
         * Especialista relacionado. Foto, nome e dataset de filtro são herdados dele.
         */
        especialista?: (number | null) | Especialista;
        /**
         * Ex: "Autoridade convidada", "Coordenação científica · Educação".
         */
        tag?: string | null;
        /**
         * Selo no rodapé da foto. Ex: "Gestão Pública · Direito constitucional".
         */
        axisBadge?: string | null;
        /**
         * Parágrafo de credencial exibido no card (≠ currículo curto do Especialista).
         */
        credencialCard?: string | null;
        /**
         * Linha "Atuação · Tribunal X" (use <strong> no valor).
         */
        metaAtuacao?: string | null;
        /**
         * Linha "Eixos · LIDERA · SIGA" (use <strong> no valor).
         */
        metaEixos?: string | null;
        ctaHref?: string | null;
        /**
         * Default no adapter: "Consultar disponibilidade".
         */
        ctaRotulo?: string | null;
        /**
         * Prefixo antes do strong. Ex: "Vinculação · ".
         */
        programasTexto?: string | null;
        programasStrong?: string | null;
        sufixoPrograma?: string | null;
        /**
         * Slug do eixo. Ex: "atencao-primaria".
         */
        area?: string | null;
        axisTag?: string | null;
        tituloAxis?: string | null;
        credencialAxis?: string | null;
        programasTextoAxis?: string | null;
        programasStrongAxis?: string | null;
        /**
         * Cor de destaque CSS (hex ou token).
         */
        styleAccent?: string | null;
        styleAccentDark?: string | null;
        /**
         * innerHTML completo do <svg> do card (path/circle/rect).
         */
        iconeSvgInner?: string | null;
        id?: string | null;
      }[]
    | null;
  credibilidade: {
    eyebrow: string;
    tituloCredibilidade: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    lede: string;
    items?:
      | {
          num: string;
          label: string;
          detalhe: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Aceita <strong>.
     */
    rodape: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
  };
  credenciamento: {
    eyebrow: string;
    tituloCredenciamento: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    descricao: string;
    lista?:
      | {
          texto: string;
          id?: string | null;
        }[]
      | null;
    ctas?:
      | {
          rotulo: string;
          href: string;
          variante: 'gold' | 'ghost-light' | 'primario' | 'secundario';
          id?: string | null;
        }[]
      | null;
    aside: {
      eyebrow: string;
      tituloAside: string;
      intro: string;
      checklist?:
        | {
            texto: string;
            id?: string | null;
          }[]
        | null;
      nota: string;
    };
  };
  faqItems?:
    | {
        /**
         * Ex: "faq-1".
         */
        id: string;
        pergunta: string;
        parags?:
          | {
              /**
               * Aceita <strong>.
               */
              texto: string;
              id?: string | null;
            }[]
          | null;
      }[]
    | null;
  ctaFinal: {
    eyebrow: string;
    /**
     * Aceita <em>.
     */
    tituloCtaFinal: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    descricao: string;
    ctaPrincipal: {
      rotulo: string;
      href: string;
      variante: 'gold' | 'ghost-light';
    };
    ctaSecundario: {
      rotulo: string;
      href: string;
      variante: 'gold' | 'ghost-light';
    };
    separadorAreas: string;
    ctasArea?:
      | {
          rotulo: string;
          href: string;
          id?: string | null;
        }[]
      | null;
  };
  stickyCta: {
    rotulo: string;
    href: string;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rodape".
 */
export interface Rodape {
  id: number;
  assinaturaInstitucional?: string | null;
  enderecoCompleto?: string | null;
  emailInstitucional: string;
  emailImprensa?: string | null;
  emailParcerias?: string | null;
  emailDpo?: string | null;
  emailSuporte?: string | null;
  emailEventos?: string | null;
  verticais?:
    | {
        vertical: 'educacao' | 'gestao-publica' | 'saude';
        email?: string | null;
        /**
         * Ex.: "opção 1"
         */
        opcaoTelefone?: string | null;
        id?: string | null;
      }[]
    | null;
  telefoneInstitucional?: string | null;
  whatsappInstitucional?: string | null;
  redesSociais?:
    | {
        rede?: ('linkedin' | 'instagram' | 'youtube' | 'facebook' | 'x' | 'tiktok') | null;
        url: string;
        id?: string | null;
      }[]
    | null;
  linksLegais?:
    | {
        rotulo: string;
        link: string;
        id?: string | null;
      }[]
    | null;
  cnpj?: string | null;
  razaoSocial?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        titulo?: T;
        subtitulo?: T;
        imagem?: T;
        ctas?:
          | T
          | {
              rotulo?: T;
              link?: T;
              variante?: T;
              id?: T;
            };
      };
  heroSlider?:
    | T
    | {
        intervaloMs?: T;
        slides?:
          | T
          | {
              tipo?: T;
              imagem?: T;
              eyebrow?: T;
              titulo?: T;
              subtitulo?: T;
              eventoPill?:
                | T
                | {
                    data?: T;
                    local?: T;
                    modalidade?: T;
                  };
              ctas?:
                | T
                | {
                    rotulo?: T;
                    link?: T;
                    variante?: T;
                    id?: T;
                  };
              id?: T;
            };
      };
  destaquesEditoriais?:
    | T
    | {
        titulo?: T;
        resumo?: T;
        imagem?: T;
        link?: T;
        eyebrow?: T;
        id?: T;
      };
  areasEmFoco?: T;
  eventosAgendaDestaque?: T;
  numerosImpacto?:
    | T
    | {
        valor?: T;
        rotulo?: T;
        id?: T;
      };
  clientesDestaque?: T;
  ctaInstitucional?:
    | T
    | {
        titulo?: T;
        descricao?: T;
        rotuloCta?: T;
        linkCta?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "o-grupo_select".
 */
export interface OGrupoSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        titulo?: T;
        subtitulo?: T;
        imagem?: T;
      };
  apresentacao?: T;
  trajetoria?: T;
  posicionamento?: T;
  numerosImpacto?:
    | T
    | {
        valor?: T;
        rotulo?: T;
        id?: T;
      };
  metodologia?: T;
  especialistasDestaque?: T;
  clientesDestaque?: T;
  ctaInstitucional?:
    | T
    | {
        titulo?: T;
        descricao?: T;
        rotuloCta?: T;
        linkCta?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "corpo-docente_select".
 */
export interface CorpoDocenteSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        titulo?: T;
        subtitulo?: T;
        quicklinks?:
          | T
          | {
              tipo?: T;
              rotulo?: T;
              href?: T;
              vertShortcut?: T;
              id?: T;
            };
      };
  metricas?:
    | T
    | {
        classe?: T;
        sublabel?: T;
        num?: T;
        label?: T;
        detalhe?: T;
        id?: T;
      };
  marker?: T;
  tituloManifesto?: T;
  lede?: T;
  archCards?:
    | T
    | {
        area?: T;
        eyebrow?: T;
        tituloArch?: T;
        descricao?: T;
        selo?: T;
        id?: T;
      };
  camadas?:
    | T
    | {
        num?: T;
        tituloCamada?: T;
        descricao?: T;
        id?: T;
      };
  callout?:
    | T
    | {
        tituloCallout?: T;
        descricao?: T;
      };
  nota?: T;
  cards?:
    | T
    | {
        formato?: T;
        especialista?: T;
        tag?: T;
        axisBadge?: T;
        credencialCard?: T;
        metaAtuacao?: T;
        metaEixos?: T;
        ctaHref?: T;
        ctaRotulo?: T;
        programasTexto?: T;
        programasStrong?: T;
        sufixoPrograma?: T;
        area?: T;
        axisTag?: T;
        tituloAxis?: T;
        credencialAxis?: T;
        programasTextoAxis?: T;
        programasStrongAxis?: T;
        styleAccent?: T;
        styleAccentDark?: T;
        iconeSvgInner?: T;
        id?: T;
      };
  credibilidade?:
    | T
    | {
        eyebrow?: T;
        tituloCredibilidade?: T;
        lede?: T;
        items?:
          | T
          | {
              num?: T;
              label?: T;
              detalhe?: T;
              id?: T;
            };
        rodape?: T;
      };
  credenciamento?:
    | T
    | {
        eyebrow?: T;
        tituloCredenciamento?: T;
        descricao?: T;
        lista?:
          | T
          | {
              texto?: T;
              id?: T;
            };
        ctas?:
          | T
          | {
              rotulo?: T;
              href?: T;
              variante?: T;
              id?: T;
            };
        aside?:
          | T
          | {
              eyebrow?: T;
              tituloAside?: T;
              intro?: T;
              checklist?:
                | T
                | {
                    texto?: T;
                    id?: T;
                  };
              nota?: T;
            };
      };
  faqItems?:
    | T
    | {
        id?: T;
        pergunta?: T;
        parags?:
          | T
          | {
              texto?: T;
              id?: T;
            };
      };
  ctaFinal?:
    | T
    | {
        eyebrow?: T;
        tituloCtaFinal?: T;
        descricao?: T;
        ctaPrincipal?:
          | T
          | {
              rotulo?: T;
              href?: T;
              variante?: T;
            };
        ctaSecundario?:
          | T
          | {
              rotulo?: T;
              href?: T;
              variante?: T;
            };
        separadorAreas?: T;
        ctasArea?:
          | T
          | {
              rotulo?: T;
              href?: T;
              id?: T;
            };
      };
  stickyCta?:
    | T
    | {
        rotulo?: T;
        href?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rodape_select".
 */
export interface RodapeSelect<T extends boolean = true> {
  assinaturaInstitucional?: T;
  enderecoCompleto?: T;
  emailInstitucional?: T;
  emailImprensa?: T;
  emailParcerias?: T;
  emailDpo?: T;
  emailSuporte?: T;
  emailEventos?: T;
  verticais?:
    | T
    | {
        vertical?: T;
        email?: T;
        opcaoTelefone?: T;
        id?: T;
      };
  telefoneInstitucional?: T;
  whatsappInstitucional?: T;
  redesSociais?:
    | T
    | {
        rede?: T;
        url?: T;
        id?: T;
      };
  linksLegais?:
    | T
    | {
        rotulo?: T;
        link?: T;
        id?: T;
      };
  cnpj?: T;
  razaoSocial?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}