/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  collections: {
    users: User;
    media: Media;
    areas: Area;
    programas: Programa;
    modulos: Modulo;
    eventos: Evento;
    especialistas: Especialista;
    conteudos: Conteudo;
    clientes: Cliente;
    leads: Lead;
    'audit-log': AuditLog;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    areas: AreasSelect<false> | AreasSelect<true>;
    programas: ProgramasSelect<false> | ProgramasSelect<true>;
    modulos: ModulosSelect<false> | ModulosSelect<true>;
    eventos: EventosSelect<false> | EventosSelect<true>;
    especialistas: EspecialistasSelect<false> | EspecialistasSelect<true>;
    conteudos: ConteudosSelect<false> | ConteudosSelect<true>;
    clientes: ClientesSelect<false> | ClientesSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    'audit-log': AuditLogSelect<false> | AuditLogSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {
    home: Home;
    'o-grupo': OGrupo;
    rodape: Rodape;
  };
  globalsSelect: {
    home: HomeSelect<false> | HomeSelect<true>;
    'o-grupo': OGrupoSelect<false> | OGrupoSelect<true>;
    rodape: RodapeSelect<false> | RodapeSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Nome completo do usuário (aparece em logs e em atribuições de Lead).
   */
  nome: string;
  /**
   * Define o escopo de acesso ao admin (DAB §10.1). Apenas super-administradores podem alterar.
   */
  perfil: 'super-admin' | 'editor-institucional' | 'editor-eventos' | 'atendimento-comercial';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Descrição alternativa para acessibilidade (WCAG 2.1 AA · CLAUDE.md §10). Imagens decorativas devem usar string vazia.
   */
  alt: string;
  /**
   * Crédito autoral exibido em legendas editoriais (ex.: "Foto: arquivo Grupo NTC").
   */
  credito?: string | null;
  /**
   * Marque quando o arquivo foi produzido pelo Grupo NTC (não derivado de fonte externa). Útil para auditoria de uso editorial.
   */
  arquivoOriginal?: boolean | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "areas".
 */
export interface Area {
  id: number;
  /**
   * Identificador interno da área.
   */
  sigla: 'educacao' | 'gestao-publica' | 'saude';
  nome: string;
  slug: string;
  eyebrow?: string | null;
  tituloHero: string;
  subtituloHero: string;
  imagemHero: number | Media;
  /**
   * Cor de acento da área (Oxford/Cardeal/Oliva). Mantém hierarquia 60·15·10·5 da Soberana 2026.
   */
  corAcento: string;
  posicionamento: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  numerosImpacto?:
    | {
        valor: string;
        rotulo: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Programas exibidos em destaque na página da área.
   */
  programasDestacados?: (number | Programa)[] | null;
  /**
   * Campos opcionais — quando vazios, o sistema usa fallback editorial automaticamente.
   */
  seo?: {
    /**
     * Título usado na SERP e em Open Graph. Máx. 60 caracteres.
     */
    tituloSeo?: string | null;
    /**
     * Meta description e Open Graph description. Máx. 160 caracteres.
     */
    descricaoSeo?: string | null;
    /**
     * Imagem Open Graph (1200×630 recomendado).
     */
    imagemOg?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programas".
 */
export interface Programa {
  id: number;
  /**
   * Ex.: PROGE, EDUTEC, PROSUS+
   */
  sigla: string;
  nomeCompleto: string;
  eyebrow?: string | null;
  area: number | Area;
  imagemCapa: number | Media;
  /**
   * Lockup SVG vertical do programa.
   */
  lockupSvg?: (number | null) | Media;
  cargaHorariaTotal: string;
  modulosQuantidade?: number | null;
  visaoGeral: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  problema?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  objetivo?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  publicoAlvo?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  eixosTematicos?:
    | {
        titulo: string;
        descricao: string;
        id?: string | null;
      }[]
    | null;
  resultadosEsperados?:
    | {
        resultado: string;
        id?: string | null;
      }[]
    | null;
  diferenciais?:
    | {
        titulo: string;
        descricao?: string | null;
        id?: string | null;
      }[]
    | null;
  coordenacaoCientifica?: (number | Especialista)[] | null;
  docentes?: (number | Especialista)[] | null;
  modalidadesEntrega?:
    | {
        tipo: 'in-company' | 'turma-aberta' | 'sob-medida' | 'hibrida';
        descricao?: string | null;
        id?: string | null;
      }[]
    | null;
  contratacaoInstitucional?: {
    disponivel?: boolean | null;
    observacoes?: string | null;
  };
  faq?:
    | {
        pergunta: string;
        resposta: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  programasRelacionados?: (number | Programa)[] | null;
  slug: string;
  /**
   * Campos opcionais — quando vazios, o sistema usa fallback editorial automaticamente.
   */
  seo?: {
    /**
     * Título usado na SERP e em Open Graph. Máx. 60 caracteres.
     */
    tituloSeo?: string | null;
    /**
     * Meta description e Open Graph description. Máx. 160 caracteres.
     */
    descricaoSeo?: string | null;
    /**
     * Imagem Open Graph (1200×630 recomendado).
     */
    imagemOg?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "especialistas".
 */
export interface Especialista {
  id: number;
  nome: string;
  slug: string;
  /**
   * Proporção 20:23 — conforme skill ntc-palestrantes.
   */
  foto: number | Media;
  titulacao: 'doutorado' | 'pos-doutorado' | 'mestrado' | 'especializacao' | 'graduacao';
  instituicao: string;
  cargoAtual?: string | null;
  /**
   * 3 a 5 linhas — destaque editorial.
   */
  curriculoCurto: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  curriculoCompleto?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  linkLattes?: string | null;
  linkLinkedin?: string | null;
  linhasAtuacao?: (number | Area)[] | null;
  /**
   * [Reservado v2 — perfil público na OTT própria]
   */
  apresentacaoOTT?: {
    ativo?: boolean | null;
    biografiaEstendida?: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "modulos".
 */
export interface Modulo {
  id: number;
  programa: number | Programa;
  numero: number;
  titulo: string;
  ementa: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  cargaHoraria?: string | null;
  /**
   * Eventos abertos que derivam deste módulo.
   */
  eventosVinculados?: (number | Evento)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "eventos".
 */
export interface Evento {
  id: number;
  nome: string;
  eyebrow?: string | null;
  /**
   * Programa do qual o evento deriva (opcional).
   */
  programa?: (number | null) | Programa;
  area: number | Area;
  imagemCapa: number | Media;
  dataInicio: string;
  dataFim?: string | null;
  fusoHorario?: string | null;
  modalidade: 'online' | 'presencial' | 'hibrido';
  local?: {
    nomeLocal?: string | null;
    endereco?: string | null;
    cidade?: string | null;
    estado?: string | null;
  };
  cargaHoraria: string;
  resumo: string;
  publicoAlvo?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  objetivos?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  conteudoProgramatico?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  programacaoDetalhada?:
    | {
        horario: string;
        titulo: string;
        descricao?: string | null;
        palestrante?: (number | Especialista)[] | null;
        id?: string | null;
      }[]
    | null;
  palestrantes?: (number | Especialista)[] | null;
  diferenciais?:
    | {
        titulo?: string | null;
        descricao?: string | null;
        id?: string | null;
      }[]
    | null;
  inscricaoAberta?: boolean | null;
  /**
   * URL da plataforma terceira de inscrição (v1).
   */
  linkInscricaoExterna?: string | null;
  /**
   * Plataforma que processa a inscrição (provisório v1).
   */
  plataformaTerceira?: ('sympla' | 'even3' | 'eventbrite' | 'webinar-atual' | 'outra') | null;
  /**
   * Ex.: "Gratuito" · "R$ 480" · "Sob proposta"
   */
  valor?: string | null;
  vagasLimitadas?: boolean | null;
  totalVagas?: number | null;
  /**
   * [Reservado v2 — OTT própria] Ativado quando plataforma própria estiver pronta.
   */
  inscricaoNativa?: {
    ativa?: boolean | null;
    idEventoOTT?: string | null;
  };
  replayDisponivel?: boolean | null;
  linkReplay?: string | null;
  prazoReplay?: string | null;
  certificadoEmitido?: boolean | null;
  observacoesCertificado?: string | null;
  eventosRelacionados?: (number | Evento)[] | null;
  faq?:
    | {
        pergunta: string;
        resposta: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  slug: string;
  /**
   * Campos opcionais — quando vazios, o sistema usa fallback editorial automaticamente.
   */
  seo?: {
    /**
     * Título usado na SERP e em Open Graph. Máx. 60 caracteres.
     */
    tituloSeo?: string | null;
    /**
     * Meta description e Open Graph description. Máx. 160 caracteres.
     */
    descricaoSeo?: string | null;
    /**
     * Imagem Open Graph (1200×630 recomendado).
     */
    imagemOg?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "conteudos".
 */
export interface Conteudo {
  id: number;
  titulo: string;
  slug: string;
  categoria: 'artigo' | 'insight' | 'publicacao' | 'material-download' | 'noticia';
  area?: (number | null) | Area;
  lide: string;
  imagemDestaque: number | Media;
  corpo: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  autor?: (number | Especialista)[] | null;
  dataPublicacao: string;
  anexoDownload?: (number | null) | Media;
  conteudosRelacionados?: (number | Conteudo)[] | null;
  /**
   * Campos opcionais — quando vazios, o sistema usa fallback editorial automaticamente.
   */
  seo?: {
    /**
     * Título usado na SERP e em Open Graph. Máx. 60 caracteres.
     */
    tituloSeo?: string | null;
    /**
     * Meta description e Open Graph description. Máx. 160 caracteres.
     */
    descricaoSeo?: string | null;
    /**
     * Imagem Open Graph (1200×630 recomendado).
     */
    imagemOg?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clientes".
 */
export interface Cliente {
  id: number;
  nome: string;
  logo: number | Media;
  esfera: 'municipal' | 'estadual' | 'federal' | 'privada' | 'terceiro-setor';
  estado?: string | null;
  cidade?: string | null;
  areasAtendidas?: (number | Area)[] | null;
  descricaoBreve?: string | null;
  destaqueHome?: boolean | null;
  ordem?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  tipo: 'proposta' | 'contato' | 'newsletter' | 'candidatura';
  identificacao?: string | null;
  status: 'novo' | 'em-atendimento' | 'qualificado' | 'descartado' | 'convertido';
  observacoesInternas?: string | null;
  nome: string;
  email: string;
  telefone?: string | null;
  cargo?: string | null;
  instituicao?: string | null;
  esfera?: ('municipal' | 'estadual' | 'federal' | 'privada' | 'terceiro-setor') | null;
  detalhesProposta?: {
    programa?: (number | null) | Programa;
    modalidade?: ('in-company' | 'turma-aberta' | 'sob-medida' | 'proposta-livre') | null;
    participantesEstimados?: number | null;
    mensagem?: string | null;
  };
  detalhesContato?: {
    assunto?: ('imprensa' | 'parcerias' | 'fornecedor' | 'duvida-institucional' | 'outro') | null;
    mensagem?: string | null;
  };
  detalhesNewsletter?: {
    areasInteresse?: (number | Area)[] | null;
  };
  detalhesCandidatura?: {
    titulacao?: string | null;
    linhasAtuacao?: (number | Area)[] | null;
    apresentacao?: string | null;
    linkLattes?: string | null;
    linkLinkedin?: string | null;
    curriculo?: (number | null) | Media;
  };
  /**
   * Página, referrer e UTMs no momento do submit.
   */
  origem?: {
    paginaSubmissao?: string | null;
    referrer?: string | null;
    utmSource?: string | null;
    utmMedium?: string | null;
    utmCampaign?: string | null;
    utmTerm?: string | null;
    utmContent?: string | null;
  };
  /**
   * Registro do aceite LGPD (CLAUDE.md §12).
   */
  consentimentoLgpd: {
    aceito: boolean;
    timestamp?: string | null;
    politicaVersao?: string | null;
    ipSubmissao?: string | null;
  };
  payloadBruto?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-log".
 */
export interface AuditLog {
  id: number;
  usuario?: (number | null) | User;
  acao?: ('criar' | 'atualizar' | 'publicar' | 'despublicar' | 'deletar' | 'login' | 'logout') | null;
  entidade?: string | null;
  entidadeId?: string | null;
  descricao?: string | null;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  ip?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'areas';
        value: number | Area;
      } | null)
    | ({
        relationTo: 'programas';
        value: number | Programa;
      } | null)
    | ({
        relationTo: 'modulos';
        value: number | Modulo;
      } | null)
    | ({
        relationTo: 'eventos';
        value: number | Evento;
      } | null)
    | ({
        relationTo: 'especialistas';
        value: number | Especialista;
      } | null)
    | ({
        relationTo: 'conteudos';
        value: number | Conteudo;
      } | null)
    | ({
        relationTo: 'clientes';
        value: number | Cliente;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'audit-log';
        value: number | AuditLog;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  nome?: T;
  perfil?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  credito?: T;
  arquivoOriginal?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "areas_select".
 */
export interface AreasSelect<T extends boolean = true> {
  sigla?: T;
  nome?: T;
  slug?: T;
  eyebrow?: T;
  tituloHero?: T;
  subtituloHero?: T;
  imagemHero?: T;
  corAcento?: T;
  posicionamento?: T;
  numerosImpacto?:
    | T
    | {
        valor?: T;
        rotulo?: T;
        id?: T;
      };
  programasDestacados?: T;
  seo?:
    | T
    | {
        tituloSeo?: T;
        descricaoSeo?: T;
        imagemOg?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programas_select".
 */
export interface ProgramasSelect<T extends boolean = true> {
  sigla?: T;
  nomeCompleto?: T;
  eyebrow?: T;
  area?: T;
  imagemCapa?: T;
  lockupSvg?: T;
  cargaHorariaTotal?: T;
  modulosQuantidade?: T;
  visaoGeral?: T;
  problema?: T;
  objetivo?: T;
  publicoAlvo?: T;
  eixosTematicos?:
    | T
    | {
        titulo?: T;
        descricao?: T;
        id?: T;
      };
  resultadosEsperados?:
    | T
    | {
        resultado?: T;
        id?: T;
      };
  diferenciais?:
    | T
    | {
        titulo?: T;
        descricao?: T;
        id?: T;
      };
  coordenacaoCientifica?: T;
  docentes?: T;
  modalidadesEntrega?:
    | T
    | {
        tipo?: T;
        descricao?: T;
        id?: T;
      };
  contratacaoInstitucional?:
    | T
    | {
        disponivel?: T;
        observacoes?: T;
      };
  faq?:
    | T
    | {
        pergunta?: T;
        resposta?: T;
        id?: T;
      };
  programasRelacionados?: T;
  slug?: T;
  seo?:
    | T
    | {
        tituloSeo?: T;
        descricaoSeo?: T;
        imagemOg?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "modulos_select".
 */
export interface ModulosSelect<T extends boolean = true> {
  programa?: T;
  numero?: T;
  titulo?: T;
  ementa?: T;
  cargaHoraria?: T;
  eventosVinculados?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "eventos_select".
 */
export interface EventosSelect<T extends boolean = true> {
  nome?: T;
  eyebrow?: T;
  programa?: T;
  area?: T;
  imagemCapa?: T;
  dataInicio?: T;
  dataFim?: T;
  fusoHorario?: T;
  modalidade?: T;
  local?:
    | T
    | {
        nomeLocal?: T;
        endereco?: T;
        cidade?: T;
        estado?: T;
      };
  cargaHoraria?: T;
  resumo?: T;
  publicoAlvo?: T;
  objetivos?: T;
  conteudoProgramatico?: T;
  programacaoDetalhada?:
    | T
    | {
        horario?: T;
        titulo?: T;
        descricao?: T;
        palestrante?: T;
        id?: T;
      };
  palestrantes?: T;
  diferenciais?:
    | T
    | {
        titulo?: T;
        descricao?: T;
        id?: T;
      };
  inscricaoAberta?: T;
  linkInscricaoExterna?: T;
  plataformaTerceira?: T;
  valor?: T;
  vagasLimitadas?: T;
  totalVagas?: T;
  inscricaoNativa?:
    | T
    | {
        ativa?: T;
        idEventoOTT?: T;
      };
  replayDisponivel?: T;
  linkReplay?: T;
  prazoReplay?: T;
  certificadoEmitido?: T;
  observacoesCertificado?: T;
  eventosRelacionados?: T;
  faq?:
    | T
    | {
        pergunta?: T;
        resposta?: T;
        id?: T;
      };
  slug?: T;
  seo?:
    | T
    | {
        tituloSeo?: T;
        descricaoSeo?: T;
        imagemOg?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "especialistas_select".
 */
export interface EspecialistasSelect<T extends boolean = true> {
  nome?: T;
  slug?: T;
  foto?: T;
  titulacao?: T;
  instituicao?: T;
  cargoAtual?: T;
  curriculoCurto?: T;
  curriculoCompleto?: T;
  linkLattes?: T;
  linkLinkedin?: T;
  linhasAtuacao?: T;
  apresentacaoOTT?:
    | T
    | {
        ativo?: T;
        biografiaEstendida?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "conteudos_select".
 */
export interface ConteudosSelect<T extends boolean = true> {
  titulo?: T;
  slug?: T;
  categoria?: T;
  area?: T;
  lide?: T;
  imagemDestaque?: T;
  corpo?: T;
  autor?: T;
  dataPublicacao?: T;
  anexoDownload?: T;
  conteudosRelacionados?: T;
  seo?:
    | T
    | {
        tituloSeo?: T;
        descricaoSeo?: T;
        imagemOg?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clientes_select".
 */
export interface ClientesSelect<T extends boolean = true> {
  nome?: T;
  logo?: T;
  esfera?: T;
  estado?: T;
  cidade?: T;
  areasAtendidas?: T;
  descricaoBreve?: T;
  destaqueHome?: T;
  ordem?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  tipo?: T;
  identificacao?: T;
  status?: T;
  observacoesInternas?: T;
  nome?: T;
  email?: T;
  telefone?: T;
  cargo?: T;
  instituicao?: T;
  esfera?: T;
  detalhesProposta?:
    | T
    | {
        programa?: T;
        modalidade?: T;
        participantesEstimados?: T;
        mensagem?: T;
      };
  detalhesContato?:
    | T
    | {
        assunto?: T;
        mensagem?: T;
      };
  detalhesNewsletter?:
    | T
    | {
        areasInteresse?: T;
      };
  detalhesCandidatura?:
    | T
    | {
        titulacao?: T;
        linhasAtuacao?: T;
        apresentacao?: T;
        linkLattes?: T;
        linkLinkedin?: T;
        curriculo?: T;
      };
  origem?:
    | T
    | {
        paginaSubmissao?: T;
        referrer?: T;
        utmSource?: T;
        utmMedium?: T;
        utmCampaign?: T;
        utmTerm?: T;
        utmContent?: T;
      };
  consentimentoLgpd?:
    | T
    | {
        aceito?: T;
        timestamp?: T;
        politicaVersao?: T;
        ipSubmissao?: T;
      };
  payloadBruto?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-log_select".
 */
export interface AuditLogSelect<T extends boolean = true> {
  usuario?: T;
  acao?: T;
  entidade?: T;
  entidadeId?: T;
  descricao?: T;
  metadata?: T;
  ip?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: number;
  hero: {
    eyebrow?: string | null;
    titulo: string;
    subtitulo?: string | null;
    imagem: number | Media;
    ctas?:
      | {
          rotulo: string;
          link: string;
          variante?: ('primario' | 'secundario') | null;
          id?: string | null;
        }[]
      | null;
  };
  destaquesEditoriais?:
    | {
        titulo: string;
        resumo: string;
        imagem: number | Media;
        link: string;
        eyebrow?: string | null;
        id?: string | null;
      }[]
    | null;
  areasEmFoco?: (number | Area)[] | null;
  /**
   * Eventos exibidos na seção de agenda da Home.
   */
  eventosAgendaDestaque?: (number | Evento)[] | null;
  numerosImpacto?:
    | {
        valor: string;
        rotulo: string;
        id?: string | null;
      }[]
    | null;
  clientesDestaque?: (number | Cliente)[] | null;
  ctaInstitucional?: {
    titulo?: string | null;
    descricao?: string | null;
    rotuloCta?: string | null;
    linkCta?: string | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "o-grupo".
 */
export interface OGrupo {
  id: number;
  hero?: {
    eyebrow?: string | null;
    titulo?: string | null;
    subtitulo?: string | null;
    imagem?: (number | null) | Media;
  };
  /**
   * Quem somos. Texto editorial curto, 2-3 parágrafos.
   */
  apresentacao?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Origens, marcos e evolução.
   */
  trajetoria?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Onde nos colocamos diante do ecossistema público.
   */
  posicionamento?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  numerosImpacto?:
    | {
        valor: string;
        rotulo: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Como entregamos. Pilares, princípios, abordagem.
   */
  metodologia?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Especialistas exibidos em destaque no /o-grupo. Em vazio, a seção é omitida.
   */
  especialistasDestaque?: (number | Especialista)[] | null;
  /**
   * Clientes exibidos em destaque no /o-grupo. Em vazio, a seção é omitida.
   */
  clientesDestaque?: (number | Cliente)[] | null;
  ctaInstitucional?: {
    titulo?: string | null;
    descricao?: string | null;
    rotuloCta?: string | null;
    linkCta?: string | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rodape".
 */
export interface Rodape {
  id: number;
  assinaturaInstitucional?: string | null;
  enderecoCompleto?: string | null;
  emailInstitucional: string;
  emailImprensa?: string | null;
  emailParcerias?: string | null;
  emailDpo?: string | null;
  telefoneInstitucional?: string | null;
  whatsappInstitucional?: string | null;
  redesSociais?:
    | {
        rede?: ('linkedin' | 'instagram' | 'youtube' | 'facebook' | 'x' | 'tiktok') | null;
        url: string;
        id?: string | null;
      }[]
    | null;
  linksLegais?:
    | {
        rotulo: string;
        link: string;
        id?: string | null;
      }[]
    | null;
  cnpj?: string | null;
  razaoSocial?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        titulo?: T;
        subtitulo?: T;
        imagem?: T;
        ctas?:
          | T
          | {
              rotulo?: T;
              link?: T;
              variante?: T;
              id?: T;
            };
      };
  destaquesEditoriais?:
    | T
    | {
        titulo?: T;
        resumo?: T;
        imagem?: T;
        link?: T;
        eyebrow?: T;
        id?: T;
      };
  areasEmFoco?: T;
  eventosAgendaDestaque?: T;
  numerosImpacto?:
    | T
    | {
        valor?: T;
        rotulo?: T;
        id?: T;
      };
  clientesDestaque?: T;
  ctaInstitucional?:
    | T
    | {
        titulo?: T;
        descricao?: T;
        rotuloCta?: T;
        linkCta?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "o-grupo_select".
 */
export interface OGrupoSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        titulo?: T;
        subtitulo?: T;
        imagem?: T;
      };
  apresentacao?: T;
  trajetoria?: T;
  posicionamento?: T;
  numerosImpacto?:
    | T
    | {
        valor?: T;
        rotulo?: T;
        id?: T;
      };
  metodologia?: T;
  especialistasDestaque?: T;
  clientesDestaque?: T;
  ctaInstitucional?:
    | T
    | {
        titulo?: T;
        descricao?: T;
        rotuloCta?: T;
        linkCta?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rodape_select".
 */
export interface RodapeSelect<T extends boolean = true> {
  assinaturaInstitucional?: T;
  enderecoCompleto?: T;
  emailInstitucional?: T;
  emailImprensa?: T;
  emailParcerias?: T;
  emailDpo?: T;
  telefoneInstitucional?: T;
  whatsappInstitucional?: T;
  redesSociais?:
    | T
    | {
        rede?: T;
        url?: T;
        id?: T;
      };
  linksLegais?:
    | T
    | {
        rotulo?: T;
        link?: T;
        id?: T;
      };
  cnpj?: T;
  razaoSocial?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}